# Generated by Django 4.0.1 on 2022-01-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章名')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('label', models.CharField(max_length=50, verbose_name='分类')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
