# Generated by Django 4.0.1 on 2022-01-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_content_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='label',
            field=models.CharField(max_length=50, verbose_name='标签'),
        ),
    ]
