# Generated by Django 4.0.1 on 2022-01-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Introduction',
            field=models.TextField(default=''),
        ),
    ]
