# Generated by Django 4.0.1 on 2022-01-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likeNum',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Introduction',
            field=models.TextField(default='', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='', verbose_name='内容'),
        ),
    ]
