# Generated by Django 4.0.1 on 2022-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_article_date_article_adddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='accessNum',
            field=models.IntegerField(default=0, verbose_name='访问次数'),
        ),
    ]
