# Generated by Django 4.1.3 on 2022-11-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_accessnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='accessNum',
        ),
        migrations.AddField(
            model_name='article',
            name='readNum',
            field=models.IntegerField(default=0, verbose_name='阅读次数'),
        ),
    ]
