# Generated by Django 4.1.3 on 2023-03-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ad_info',
            field=models.JSONField(verbose_name='地区信息'),
        ),
    ]
