# Generated by Django 4.1.3 on 2023-03-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_userinfo_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='index',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='序号'),
        ),
    ]
