# Generated by Django 4.1.3 on 2023-03-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_userinfo_id_userinfo_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='time',
            field=models.TimeField(auto_created=True, verbose_name='时间'),
        ),
    ]
